/**
 * Тексты кейса Skyway (RU / EN): статичная разметка (`Skyway.astro`) и живые экраны (`src/scripts/skyway.ts`).
 * Все строки сразу проходят через typograph(): HTML внутри — только <b> и <br>, без атрибутов.
 */
import { typograph } from '../../../i18n/typograph';

type Pair = { no: string; problem: string; solution: string };
type Screen = { title: string; pairs: Pair[] };

const RU = {
  title: 'Агрегаторы авиабилетов',
  eyebrow: 'Case 02 · Travel booking',
  lead: [
    'Мы разбираем проблемы, с которыми реальные люди сталкиваются при покупке билетов на агрегаторах.',
    'Покупку билета бросают чаще, чем любую другую онлайн-покупку. В интернет-магазинах до оплаты не доходят около 70% корзин, а в путешествиях — больше 80%. Главная причина — неожиданные доплаты: почти половина покупателей уходит, когда к итоговой цене добавляются сборы, багаж и выбор места. Ещё четверть бросает покупку, если перед оплатой нужно завести аккаунт.',
  ],
  leadListTitle: 'Часть проблем всплывает уже после оплаты:',
  leadList: [
    'Сколько денег вернут за билет, человек узнаёт, только когда пытается его сдать',
    'Опечатку в паспортных данных замечают на стойке регистрации в аэропорту',
    'Карту мест, где свободные и занятые места отличаются только цветом, не может прочитать каждый двенадцатый мужчина: около 8% мужчин плохо различают цвета',
  ],
  problemsTitle: '15 проблем — 4 экрана',
  problems: [
    ['Цена растёт к оплате', 'Багаж, сервисный сбор и место добавляются на последних шагах. Скрытые доплаты — главная причина брошенных бронирований в тревеле.', [1, 4]],
    ['Тарифы — шифровка', '«Возврат с удержанием» без суммы. Условия становятся понятны, когда планы уже поменялись.', [2]],
    ['Опасные стыковки', 'Два отдельных билета выглядят как обычная пересадка. Если первый рейс задержат, второй билет сгорает.', [1]],
    ['Семью рассаживают', 'Сидеть вместе предлагают за доплату, а пропуск выбора места пугает.', [3]],
    ['Ошибка в данных', 'Опечатка в номере паспорта — переоформление или отказ в посадке.', [4]],
    ['Давление и навязывание', 'Фейковые «осталось 2 места», таймеры-страшилки, страховка, включённая по умолчанию.', [2, 4]],
    ['Купить сейчас или ждать?', 'Цены скачут, и непонятно, хорошая ли цена. Человек открывает десяток вкладок или уходит «подумать».', [1]],
    ['«Лучший» = кто заплатил', 'Порядок выдачи непрозрачен: на агрегаторах есть платные размещения, и «рекомендуем» перестаёт вызывать доверие.', [1]],
    ['Ручная кладь лоукоста', '«Ручная кладь включена» — но только рюкзак 36×30×27. Чемодан на колёсах придётся оплатить у выхода на посадку.', [1]],
    ['Путаница с ночными рейсами', 'Рейс в 00:30 «12-го» — это ночь с 11-го на 12-е. Люди приезжают в аэропорт на сутки позже.', [1, 4]],
    ['«Обмен за 1 500 ₽» — не вся правда', 'К штрафу добавляется разница в цене, и об этом узнают только при обмене.', [2]],
    ['Аварийный ряд', 'Место «с доп. пространством» покупают с ребёнком — на посадке пересаживают, деньги не возвращают.', [3]],
    ['Карта мест недоступна', 'Статусы мест различаются только цветом — дальтоникам и пользователям скринридеров карта не читается.', [3]],
    ['Обязательная регистрация', 'Регистрацию требуют перед оплатой. Это одна из частых причин бросить покупку в e-commerce.', [4]],
    ['«Деньги списали, а билета нет»', 'Сбой выписки — частый сценарий жалоб. Страх двойного списания тормозит оплату.', [4]],
  ] as [string, string, number[]][],
  toScreens: (s: number[]) => (s.length > 1 ? `→ экраны ${s.join(' и ')}` : `→ экран ${s[0]}`),
  screensTitle: 'Решение',
  pos: (a: string, n: number) => `${a} из ${n}`,
  prev: 'Предыдущий экран',
  next: 'Следующий экран',
  problem: 'Проблема · ',
  solution: 'Решение · ',
  screens: [
    {
      title: '1 · Выдача рейсов',
      pairs: [
        { no: '01', problem: 'лоукост дешевле всех, пока не добавишь багаж; цена «от» за одного и без сборов.', solution: 'переключатель «Мне нужен багаж» пересчитывает цены и порядок рейсов. Цены со всеми сборами, сразу за двоих.' },
        { no: '03', problem: 'самостоятельная стыковка выглядит как обычная.', solution: 'отдельная метка, объяснение риска и реальная статистика опозданий первого рейса.' },
        { no: '07', problem: 'непонятно, хорошая ли цена.', solution: 'сравнение с обычной ценой на направлении и подписка «Следить» вместо десятка вкладок.' },
        { no: '08', problem: 'Бейдж «Рекомендуем» не вызывает доверия.', solution: 'тап по «Оптимальный» объясняет формулу. Платных мест в выдаче нет, и это сказано прямо.' },
        { no: '09', problem: '«кладь включена» — а чемодан не пустят.', solution: 'размер ручной клади у лоукоста показан прямо в карточке.' },
        { no: '10', problem: 'прилёт «+1» легко пропустить.', solution: 'у ночных рейсов вместо «+1» написан день недели и дата прилёта.' },
      ],
    },
    {
      title: '2 · Выбор тарифа',
      pairs: [
        { no: '02', problem: '«Возврат с удержанием» — а сколько удержат?', solution: 'таблица с суммами в рублях. Подсказка считает за пользователя: «Лайт + багаж в аэропорту = дороже Стандарта».' },
        { no: '11', problem: '«обмен за 1 500 ₽», а потом ещё доплата.', solution: 'в таблице прямо написано «+ разница в цене», а подсказка объясняет это на примере.' },
        { no: '06', problem: '«осталось 2 места» и бейджи «хит».', solution: 'никакой искусственной срочности, только условия. Кликайте по колонкам.' },
      ],
    },
    {
      title: '3 · Места',
      pairs: [
        { no: '04', problem: 'чтобы сесть рядом, приходится платить или искать места вручную.', solution: '«Посадить Ивана рядом?» — одна кнопка, только бесплатные места. Пропуск — заметная ссылка с объяснением.' },
        { no: '01', problem: 'доплата за место всплывает на оплате.', solution: 'цена в легенде, итог пересчитывается сразу. На «Флекс» места с доп. пространством бесплатны: экраны связаны.' },
        { no: '12', problem: 'место у аварийного выхода покупают, а на посадке пересаживают.', solution: 'при выборе ряда 6 сразу видны ограничения. Попробуйте выбрать место в 6 ряду.' },
        { no: '13', problem: 'статусы мест различаются только цветом.', solution: 'у платных мест есть «+», у занятых штриховка. Каждое место — кнопка с понятной подписью для скринридера, по карте можно ходить клавиатурой.' },
      ],
    },
    {
      title: '4 · Оформление и оплата',
      pairs: [
        { no: '01·06', problem: '«цена изменилась» на последнем шаге, таймеры-страшилки, страховка по умолчанию.', solution: 'цена закреплена на 18 минут без давления. Страховка выключена. В разбивке «сервисный сбор 0 ₽»: итог совпадает с первым экраном.' },
        { no: '05', problem: 'опечатка в паспорте всплывает в аэропорту.', solution: 'скан паспорта, сохранённые пассажиры и проверка при вводе. Поправьте номер, и кнопка оплаты станет активной.' },
        { no: '10', problem: 'ошибка в дате вылета.', solution: 'тёмная плашка повторяет главное: день недели, дату, «утра/ночи» и аэропорты.' },
        { no: '14', problem: 'перед оплатой требуют регистрацию.', solution: 'достаточно почты или телефона, аккаунт можно создать потом.' },
        { no: '15', problem: 'страшно оплатить и остаться без билета.', solution: 'прямо под кнопкой обещание: если билет не оформится, деньги вернутся автоматически' },
      ],
    },
  ] as Screen[],
  // Экран 1
  from: 'Москва',
  to: 'Сочи',
  routeSub: '12 окт · 2 взрослых · эконом',
  insight: 'Цены на 12 окт <b>на 11% ниже обычного</b> для этого направления',
  follow: '🔔 Следить',
  followOn: '✓ Сообщим о снижении',
  bag: 'Мне нужен багаж',
  bagOn: 'Цены с багажом 23 кг и всеми сборами',
  bagOff: 'Только ручная кладь. Цены со всеми сборами',
  days: [['пн', 9, '7 980'], ['вт', 10, '7 610'], ['ср', 11, '6 990', 1], ['чт', 12, '7 340', 0, 1], ['пт', 13, '9 880'], ['сб', 14, '11 400']] as [string, number, string, number?, number?][],
  airlines: ['Аэро Норд', 'Ветер · лоукост', 'Юг Авиа + Ветер', 'Аэро Норд'],
  durations: ['2 ч 45 мин', '2 ч 50 мин', '7 ч 20 мин', '2 ч 30 мин'],
  hand: 'Ручная кладь — только рюкзак 36×30×27 см. Чемодан на колёсах — 2 400 ₽ у выхода на посадку',
  selfStop: 'Волгоград · 1 ч 40 м',
  arrDay: 'пт, 13 окт',
  tagBest: '★ Оптимальный',
  tagCheap: '↓ Дешевле всех',
  tagFast: '⚡ Быстрее всех',
  tagSelf: '⚠ Самостоятельная пересадка',
  tagBag: 'багаж включён',
  tagNoBag: 'без багажа',
  why: '<b>Как считаем «оптимальный»:</b> цена + время в пути + надёжность стыковки. Платных мест в выдаче нет — авиакомпании не могут купить позицию.',
  direct: 'прямой',
  selfAlert: '<b>Два отдельных билета.</b> Багаж получаете и сдаёте сами. Если первый рейс задержат, второй билет не вернут. Первый рейс опаздывает на 40+ мин в 1 из 5 полётов.',
  forTwo: (p: string) => `${p} ₽ за двоих, всё включено`,
  // Экран 2
  fareTop: 'Тариф',
  step: (n: number) => `шаг ${n} из 3`,
  fareFlight: 'Аэро Норд · 12 окт, 06:40 → 09:25 · прямой',
  honest: 'Условия обмена и возврата — из правил перевозчика, в рублях. Никаких «по правилам тарифа».',
  allIn: 'Всё включено,<br>без доплат дальше',
  fares: { lite: 'Лайт', std: 'Стандарт', flex: 'Флекс' },
  fareChange: { lite: '3 500 ₽ + разница', std: '1 500 ₽ + разница', flex: '0 ₽ + разница' },
  fareRefund: { lite: 'только сборы', std: '−2 500 ₽', flex: 'полностью' },
  fareRows: ['Ручная кладь 10 кг', 'Багаж 23 кг', 'Место с доп. пространством', 'Обмен', 'Возврат'],
  perPax: 'за 1 пасс.',
  tips: {
    lite: '<b>Лайт без багажа.</b> Если всё же понадобится чемодан, в аэропорту он обойдётся в 2 900 ₽ — итого <b>8 890 ₽</b>, на 1 550 ₽ дороже «Стандарта».',
    std: '<b>Стандарт: багаж включён.</b> Обмен — 1 500 ₽ плюс разница, если новый рейс дороже. Например, перенос на пятницу (9 880 ₽): 1 500 + 2 540 = <b>4 040 ₽</b> с человека.',
    flex: (d: string) => `<b>Флекс: полная гибкость.</b> Обмен без штрафа (платите только разницу в цене), возврат полный до вылета. Переплата за гибкость — ${d} ₽ с человека по сравнению со «Стандартом».`,
  },
  paxFare: (f: string) => `2 пассажира · ${f}`,
  forTwoShort: 'за двоих',
  goFare: (f: string) => `Продолжить с «${f}»`,
  // Экран 3
  seatsTop: 'Места',
  free: 'Бесплатно',
  xl: 'Больше места +900 ₽',
  xlFree: 'Больше места · бесплатно на Флекс',
  taken: 'Занято',
  regularFree: 'Обычные места<br>бесплатно',
  skip: 'Пропустить — места назначат бесплатно при регистрации',
  names: ['Анна', 'Иван'],
  acc: ['Анну', 'Ивана'],
  pax: (n: number) => `Пассажир ${n}`,
  choose: 'выберите',
  together: '<b>Вы сидите рядом</b>',
  seatNear: (who: string, seat: string) => `<b>Посадить ${who} рядом?</b>${seat} свободно и бесплатно`,
  yes: 'Да',
  pairMsg: '<b>Посадим вас рядом бесплатно</b>Подберём 2 обычных места подряд',
  pick: 'Подобрать',
  exitL: '◀ ВЫХОД',
  exitR: 'ВЫХОД ▶',
  seatTaken: (id: string) => `Место ${id}, занято`,
  seatMine: (id: string, who: string) => `Место ${id}, выбрано для: ${who}`,
  seatFree: (id: string, paid: boolean, exit: boolean) => `Место ${id}, ${paid ? 'доплата 900 рублей' : 'бесплатно'}${exit ? ', ряд у аварийного выхода' : ''}`,
  exitWarn: (s: string) => `<b>${s} — ряд у аварийного выхода.</b> Только для пассажиров 18+, без детей и животных, готовых помочь экипажу. Иначе пересадят при посадке.`,
  seatsLine: (f: string, s: string) => `${f} · места ${s}`,
  total: 'итого',
  chooseFor: (n: string) => `Выберите место для: ${n}`,
  cont: 'Продолжить',
  // Экран 4
  checkTop: 'Оформление',
  tripDay: 'Чт, 12 октября',
  tripTime: '· вылет 06:40 утра',
  locked: '<b>Цена закреплена.</b> Потом проверим заново, данные сохранятся',
  saved: '✓ из сохранённых',
  passport: 'Паспорт РФ •• 4821',
  scan: 'Сканировать паспорт',
  fields: ['Фамилия', 'Имя', 'Дата рождения', 'Серия и номер'],
  fieldValues: ['Ковалёв', 'Иван'],
  passenger1: 'Анна Ковалёва',
  contact: 'Билеты пришлём на почту или телефон',
  noReg: 'без регистрации',
  ins: '<b>Страховка от невыезда · 690 ₽</b>',
  insSub: 'Необязательно. Вернёт стоимость билетов при болезни',
  toPay: 'К оплате',
  brkShow: 'Из чего цена ▾',
  brkHide: 'Скрыть ▴',
  fine: '<b>Отмена бесплатно 24 часа.</b> Если билет не оформится, деньги вернутся автоматически',
  docOk: '✓ Номер паспорта в порядке',
  docBad: (n: number) => `Серия и номер — 10 цифр, сейчас ${n}. Проверьте по паспорту`,
  brkTickets: (f: string, p: string) => `Билеты «${f}», 2 × ${p} ₽`,
  brkSeats: (s: string) => `Места ${s}`,
  atCheckin: 'при регистрации',
  brkIns: 'Страховка',
  none: 'нет',
  brkFee: 'Сервисный сбор',
  feeIn: '0 ₽ · уже в цене',
  pay: (p: string) => `Оплатить ${p} ₽`,
  fixDoc: 'Проверьте номер паспорта Ивана',
  ariaBag: 'Багаж',
  ariaIns: 'Страховка',
};

const EN: typeof RU = {
  title: 'Flight booking aggregators',
  eyebrow: 'Case 02 · Travel booking',
  lead: [
    'We look at the problems real people run into when buying tickets on flight aggregators.',
    'People abandon flight bookings more often than any other online purchase. In online stores about 70% of carts never reach payment; in travel it is over 80%. The main reason is surprise fees: almost half of shoppers leave when taxes, baggage and seat selection are added to the total. Another quarter give up if they have to create an account before paying.',
  ],
  leadListTitle: 'Some problems surface only after payment:',
  leadList: [
    'People find out how much they will get back for a ticket only when they try to return it',
    'A typo in passport details is noticed at the airport check-in desk',
    'One in twelve men cannot read a seat map where free and taken seats differ only by color: about 8% of men have color vision deficiency',
  ],
  problemsTitle: '15 problems — 4 screens',
  problems: [
    ['The price grows at checkout', 'Baggage, a service fee and a seat get added at the last steps. Hidden extras are the main reason for abandoned bookings in travel.', [1, 4]],
    ['Fares are a cipher', '“Refund with a deduction” with no amount. The terms become clear only after your plans have changed.', [2]],
    ['Risky connections', 'Two separate tickets look like a normal connection. If the first flight is delayed, the second ticket is lost.', [1]],
    ['Families get split up', 'Sitting together costs extra, and skipping seat selection is scary.', [3]],
    ['Mistakes in the data', 'A typo in the passport number means reissuing the ticket or being denied boarding.', [4]],
    ['Pressure and upselling', 'Fake “2 seats left”, scary timers, insurance switched on by default.', [2, 4]],
    ['Buy now or wait?', 'Prices jump, and it’s unclear whether the price is good. People open a dozen tabs or leave “to think it over”.', [1]],
    ['“Best” = who paid', 'The order of results is opaque: aggregators sell placements, and “recommended” stops being trusted.', [1]],
    ['Low-cost carry-on', '“Carry-on included” — but only a 36×30×27 backpack. A wheeled suitcase has to be paid for at the gate.', [1]],
    ['Night flight confusion', 'A 00:30 flight “on the 12th” is the night from the 11th to the 12th. People arrive at the airport a day late.', [1, 4]],
    ['“Change for 1,500 ₽” isn’t the whole truth', 'The fare difference is added to the fee, and people learn about it only when they change the ticket.', [2]],
    ['The exit row', 'A seat “with extra legroom” is bought for a trip with a child — at boarding they get moved, and the money isn’t refunded.', [3]],
    ['The seat map is inaccessible', 'Seat statuses differ only by colour — the map is unreadable for colour-blind and screen reader users.', [3]],
    ['Forced sign-up', 'Sign-up is required before payment. It’s one of the common reasons to abandon a purchase in e-commerce.', [4]],
    ['“Charged, but no ticket”', 'A ticketing failure is a common complaint. The fear of being charged twice slows down payment.', [4]],
  ],
  toScreens: (s) => (s.length > 1 ? `→ screens ${s.join(' and ')}` : `→ screen ${s[0]}`),
  screensTitle: 'Solution',
  pos: (a, n) => `${a} of ${n}`,
  prev: 'Previous screen',
  next: 'Next screen',
  problem: 'Problem · ',
  solution: 'Solution · ',
  screens: [
    {
      title: '1 · Flight results',
      pairs: [
        { no: '01', problem: 'the low-cost carrier is the cheapest until you add baggage; the price is “from”, per person and without fees.', solution: 'the “I need checked baggage” toggle recalculates prices and the order of flights. Prices include all fees, for two at once.' },
        { no: '03', problem: 'a self-transfer looks like a normal connection.', solution: 'a separate label, an explanation of the risk and real delay statistics of the first flight.' },
        { no: '07', problem: 'it’s unclear whether the price is good.', solution: 'a comparison with the usual price on the route and a “Track” subscription instead of a dozen tabs.' },
        { no: '08', problem: 'The “Recommended” badge isn’t trusted.', solution: 'tapping “Best” explains the formula. There are no paid placements in the results, and this is said plainly.' },
        { no: '09', problem: '“carry-on included” — but the suitcase won’t be allowed.', solution: 'the low-cost carry-on size is shown right in the card.' },
        { no: '10', problem: 'an arrival “+1” is easy to miss.', solution: 'night flights show the weekday and arrival date instead of “+1”.' },
      ],
    },
    {
      title: '2 · Choosing a fare',
      pairs: [
        { no: '02', problem: '“Refund with a deduction” — but how much?', solution: 'a table with amounts in rubles. The hint does the math for the user: “Lite + baggage at the airport = more than Standard”.' },
        { no: '11', problem: '“change for 1,500 ₽”, and then an extra charge.', solution: 'the table plainly says “+ fare difference”, and the hint explains it with an example.' },
        { no: '06', problem: '“2 seats left” and “bestseller” badges.', solution: 'no artificial urgency, only the terms. Click the columns.' },
      ],
    },
    {
      title: '3 · Seats',
      pairs: [
        { no: '04', problem: 'to sit together you have to pay or look for seats manually.', solution: '“Seat Ivan next to you?” — one button, free seats only. Skipping is a visible link with an explanation.' },
        { no: '01', problem: 'the seat fee pops up at payment.', solution: 'the price is in the legend, and the total updates at once. On Flex, extra-legroom seats are free: the screens are connected.' },
        { no: '12', problem: 'an exit-row seat is bought, and at boarding the passenger is moved.', solution: 'choosing row 6 shows the restrictions right away. Try picking a seat in row 6.' },
        { no: '13', problem: 'seat statuses differ only by colour.', solution: 'paid seats have a “+”, taken ones are hatched. Every seat is a button with a clear label for screen readers, and the map can be navigated with the keyboard.' },
      ],
    },
    {
      title: '4 · Checkout and payment',
      pairs: [
        { no: '01·06', problem: '“the price has changed” at the last step, scary timers, insurance by default.', solution: 'the price is locked for 18 minutes without pressure. Insurance is off. The breakdown says “service fee 0 ₽”: the total matches the first screen.' },
        { no: '05', problem: 'a typo in the passport surfaces at the airport.', solution: 'passport scan, saved passengers and validation while typing. Fix the number, and the pay button becomes active.' },
        { no: '10', problem: 'a mistake in the departure date.', solution: 'the dark bar repeats the essentials: weekday, date, “am/pm” and airports.' },
        { no: '14', problem: 'sign-up is required before payment.', solution: 'an email or phone is enough, an account can be created later.' },
        { no: '15', problem: 'it’s scary to pay and be left without a ticket.', solution: 'a promise right under the button: if the ticket isn’t issued, the money comes back automatically' },
      ],
    },
  ],
  from: 'Moscow',
  to: 'Sochi',
  routeSub: '12 Oct · 2 adults · economy',
  insight: 'Prices on 12 Oct are <b>11% below usual</b> for this route',
  follow: '🔔 Track',
  followOn: '✓ We’ll alert you',
  bag: 'I need checked baggage',
  bagOn: 'Prices with 23 kg baggage and all fees',
  bagOff: 'Carry-on only. Prices with all fees',
  days: [['Mon', 9, '7,980'], ['Tue', 10, '7,610'], ['Wed', 11, '6,990', 1], ['Thu', 12, '7,340', 0, 1], ['Fri', 13, '9,880'], ['Sat', 14, '11,400']],
  airlines: ['Aero Nord', 'Veter · low-cost', 'Yug Avia + Veter', 'Aero Nord'],
  durations: ['2 h 45 min', '2 h 50 min', '7 h 20 min', '2 h 30 min'],
  hand: 'Carry-on — backpack only, 36×30×27 cm. A wheeled suitcase costs 2,400 ₽ at the gate',
  selfStop: 'Volgograd · 1 h 40 m',
  arrDay: 'Fri, 13 Oct',
  tagBest: '★ Best',
  tagCheap: '↓ Cheapest',
  tagFast: '⚡ Fastest',
  tagSelf: '⚠ Self-transfer',
  tagBag: 'baggage included',
  tagNoBag: 'no baggage',
  why: '<b>How we pick “best”:</b> price + travel time + connection reliability. There are no paid placements in the results — airlines can’t buy a position.',
  direct: 'nonstop',
  selfAlert: '<b>Two separate tickets.</b> You collect and re-check your baggage yourself. If the first flight is delayed, the second ticket won’t be refunded. The first flight is 40+ min late on 1 in 5 flights.',
  forTwo: (p) => `${p} ₽ for two, all inclusive`,
  fareTop: 'Fare',
  step: (n) => `step ${n} of 3`,
  fareFlight: 'Aero Nord · 12 Oct, 06:40 → 09:25 · nonstop',
  honest: 'Change and refund terms come from the carrier’s rules, in rubles. No “according to the fare rules”.',
  allIn: 'All inclusive,<br>no extras later',
  fares: { lite: 'Lite', std: 'Standard', flex: 'Flex' },
  fareChange: { lite: '3,500 ₽ + difference', std: '1,500 ₽ + difference', flex: '0 ₽ + difference' },
  fareRefund: { lite: 'fees only', std: '−2,500 ₽', flex: 'in full' },
  fareRows: ['Carry-on 10 kg', 'Baggage 23 kg', 'Extra-legroom seat', 'Change', 'Refund'],
  perPax: 'per pax',
  tips: {
    lite: '<b>Lite without baggage.</b> If you still need a suitcase, it costs 2,900 ₽ at the airport — <b>8,890 ₽</b> in total, 1,550 ₽ more than Standard.',
    std: '<b>Standard: baggage included.</b> A change costs 1,500 ₽ plus the difference if the new flight is more expensive. For example, moving to Friday (9,880 ₽): 1,500 + 2,540 = <b>4,040 ₽</b> per person.',
    flex: (d) => `<b>Flex: full flexibility.</b> Changes without a fee (you pay only the fare difference), full refund before departure. Flexibility costs ${d} ₽ more per person than Standard.`,
  },
  paxFare: (f) => `2 passengers · ${f}`,
  forTwoShort: 'for two',
  goFare: (f) => `Continue with ${f}`,
  seatsTop: 'Seats',
  free: 'Free',
  xl: 'Extra legroom +900 ₽',
  xlFree: 'Extra legroom · free on Flex',
  taken: 'Taken',
  regularFree: 'Regular seats<br>are free',
  skip: 'Skip — seats will be assigned for free at check-in',
  names: ['Anna', 'Ivan'],
  acc: ['Anna', 'Ivan'],
  pax: (n) => `Passenger ${n}`,
  choose: 'choose',
  together: '<b>You’re sitting together</b>',
  seatNear: (who, seat) => `<b>Seat ${who} next to you?</b>${seat} is free of charge`,
  yes: 'Yes',
  pairMsg: '<b>We’ll seat you together for free</b>Two regular seats in a row',
  pick: 'Find',
  exitL: '◀ EXIT',
  exitR: 'EXIT ▶',
  seatTaken: (id) => `Seat ${id}, taken`,
  seatMine: (id, who) => `Seat ${id}, selected for ${who}`,
  seatFree: (id, paid, exit) => `Seat ${id}, ${paid ? '900 rubles extra' : 'free'}${exit ? ', exit row' : ''}`,
  exitWarn: (s) => `<b>${s} — exit row.</b> Only for passengers 18+, without children or pets, ready to help the crew. Otherwise you’ll be moved at boarding.`,
  seatsLine: (f, s) => `${f} · seats ${s}`,
  total: 'total',
  chooseFor: (n) => `Choose a seat for ${n}`,
  cont: 'Continue',
  checkTop: 'Checkout',
  tripDay: 'Thu, 12 October',
  tripTime: '· departs 06:40 am',
  locked: '<b>The price is locked.</b> We’ll recheck it later, your data will be saved',
  saved: '✓ saved',
  passport: 'Russian passport •• 4821',
  scan: 'Scan passport',
  fields: ['Last name', 'First name', 'Date of birth', 'Series and number'],
  fieldValues: ['Kovalev', 'Ivan'],
  passenger1: 'Anna Kovaleva',
  contact: 'We’ll send tickets to your email or phone',
  noReg: 'no sign-up',
  ins: '<b>Trip cancellation insurance · 690 ₽</b>',
  insSub: 'Optional. Refunds the tickets if you fall ill',
  toPay: 'To pay',
  brkShow: 'Price breakdown ▾',
  brkHide: 'Hide ▴',
  fine: '<b>Free cancellation for 24 hours.</b> If the ticket isn’t issued, the money comes back automatically',
  docOk: '✓ The passport number is fine',
  docBad: (n) => `Series and number — 10 digits, now ${n}. Check your passport`,
  brkTickets: (f, p) => `${f} tickets, 2 × ${p} ₽`,
  brkSeats: (s) => `Seats ${s}`,
  atCheckin: 'at check-in',
  brkIns: 'Insurance',
  none: 'none',
  brkFee: 'Service fee',
  feeIn: '0 ₽ · already included',
  pay: (p) => `Pay ${p} ₽`,
  fixDoc: 'Check Ivan’s passport number',
  ariaBag: 'Baggage',
  ariaIns: 'Insurance',
};

/** Применяет typograph ко всем строкам и строкам, которые возвращают функции. */
function deep<T>(v: T): T {
  // Текст между тегами — по отдельности: короткое слово сразу после <b> или <br> тоже привязывается.
  if (typeof v === 'string') return v.split(/(<[^>]+>)/).map((part) => (part.startsWith('<') ? part : typograph(part))).join('') as T;
  if (typeof v === 'function') return ((...a: unknown[]) => deep((v as (...x: unknown[]) => unknown)(...a))) as T;
  if (Array.isArray(v)) return v.map(deep) as T;
  if (v && typeof v === 'object') return Object.fromEntries(Object.entries(v).map(([k, x]) => [k, deep(x)])) as T;
  return v;
}

export const COPY = { ru: deep(RU), en: deep(EN) };
export type SkyCopy = typeof RU;
